name: Build and Deploy to AWS

on:
  workflow_dispatch:

env:
  AWS_REGION: us-east-1
  PATIENT_REPO: 082041771564.dkr.ecr.us-east-1.amazonaws.com/uc8-patient
  APPOINTMENT_REPO: 082041771564.dkr.ecr.us-east-1.amazonaws.com/uc8-appointment

permissions:
  id-token: write
  contents: write

jobs:
  build-push-deploy:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: usecase8

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Login to Amazon ECR
        uses: aws-actions/amazon-ecr-login@v2

      # Patient Service build & push
      - name: Build patient-service Docker image
        run: |
          docker build -t 082041771564.dkr.ecr.us-east-1.amazonaws.com/uc8-patient:latest ./application/patient-service
          docker push 082041771564.dkr.ecr.us-east-1.amazonaws.com/uc8-patient:latest

      # Appointment Service build & push
      - name: Build appointment-service Docker image
        run: |
          docker build -t 082041771564.dkr.ecr.us-east-1.amazonaws.com/uc8-appointment:latest ./application/appointment-service
          docker push 082041771564.dkr.ecr.us-east-1.amazonaws.com/uc8-appointment:latest

      # Terraform deploy
      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Init
        run: terraform init -reconfigure

      - name: Terraform Plan
        run: terraform plan

      - name: Terraform Apply
        run: terraform apply -auto-approve
